# Generated by Django 6.0.6 on 2026-06-09 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at']},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='movie',
            name='recap_end',
            field=models.IntegerField(default=0, help_text='Recap end in seconds'),
        ),
        migrations.AddField(
            model_name='movie',
            name='recap_start',
            field=models.IntegerField(default=0, help_text='Recap start in seconds'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='fan_profiles', to='core.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hls_stream_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='intro_end',
            field=models.IntegerField(default=0, help_text='Intro end in seconds'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='intro_start',
            field=models.IntegerField(default=0, help_text='Intro start in seconds'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='next_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_episode', to='core.movie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='A', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('profile', 'movie')},
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('stream_url', models.URLField()),
                ('is_default', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='core.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('file_url', models.URLField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_forced', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='core.movie')),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('bitrate', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField()),
                ('is_default', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='core.movie')),
            ],
        ),
    ]
